name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Generate CHANGELOG.md
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install
      run: installChangeLog.bat
      shell: cmd
      
    - name: Make
      run: makeChangeLog.bat
      shell: cmd
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ## see https://github.com/actions/upload-artifact
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: CHANGELOG
        path: 'CHANGELOG*.md'

    # ログのアップロード
    # 失敗時も行うため always() を指定する
    # %TEMP% に直接アクセスできないので TempPath を設定する
    - name: set env TEMP
      if: always()
      shell: cmd
      run: |
         echo %TEMP%
         echo ::set-env name=TempPath::%TEMP%
    - name: Upload log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: log
        path: ${{ env.TempPath }}\github-changelog-logger.log
